spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=pRmHnjRFNBMgvuXOfCKGNawUlzGHFtgh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

libgo.token.key=${LIBGO_TOKEN_KEY}
libgo.token.expiry=${LIBGO_TOKEN_EXPIRY}

server.port=${PORT:8080}
spring.security.enabled=true

resend.api.key=${RESEND_API_KEY}
libgo.app.url=${LIBGO_APP_URL}